INSERT INTO `equipment_category` VALUES (1,'armor','Armor','/api/equipment-category/armor'),
(2,'heavy-armor','Heavy Armor', '/api/equipment-category/heavy-armor'),
(3,'light-armor','Light Armor', '/api/equipment-category/light-armor'),
(4,'medium-armor','Medium Armor', '/api/equipment-category/medium-armor'),
(5,'martial-melee-weapons','Martial Melee Weapons', '/api/equipment-category/martial-melee-weapons'),
(6,'martial-ranged-weapons','Martial Ranged Weapons', '/api/equipment-category/martial-ranged-weapons'),
(7,'martial-weapons','Martial Weapons', '/api/equipment-category/martial-weapons'),
(8,'melee-weapons','Melee Weapons', '/api/equipment-category/melee-weapons'),
(9,'ranged-weapons','Ranged Weapons', '/api/equipment-category/ranged-weapons'),
(10,'simple-melee-weapons','Simple Melee Weapons', '/api/equipment-category/simple-melee-weapons'),
(11,'simple-ranged-weapons','Simple Ranged Weapons', '/api/equipment-category/simple-ranged-weapons'),
(12,'simple-weapons','Simple Weapons', '/api/equipment-category/simple-weapons'),
(13,'staff','Staff', '/api/equipment-category/staff'),
(14,'wand','Wand', '/api/equipment-category/wand'),
(15,'weapon','Weapon', '/api/equipment-category/weapon'),
(16,'ammunition','Ammunition', '/api/equipment-category/ammunition'),
(17,'arcane-focus','Arcane Focus', '/api/equipment-category/arcane-focus'),
(18,'druidic-focus','Druidic Focus', '/api/equipment-category/druidic-focus'),
(19,'holy-symbols','Holy Symbols', '/api/equipment-category/holy-symbols'),
(20,'potion','Potion', '/api/equipment-category/potion'),
(21,'other-tools','Other Tools', '/api/equipment-category/other-tools'),
(22,'shields','Shields', '/api/equipment-category/shields'),
(23,'scroll','Scroll', '/api/equipment-category/scroll'),
(24,'rod','Rod', '/api/equipment-category/rod'),
(25,'ring','Ring', '/api/equipment-category/ring'),
(26,'tools','Tools', '/api/equipment-category/tools'),
(27,'standard-gear','Standard Gear', '/api/equipment-category/standard-gear'),
(28,'adventuring-gear','Adventuring Gear', '/api/equipment-category/adventuring-gear'),
(29,'artisans-tools','Artisan\'s Tools', '/api/equipment-category/artisans-tools'),
(30,'equipment-packs','Equipment Packs', '/api/equipment-category/equipment-packs'),
(31,'gaming-sets','Gaming Sets', '/api/equipment-category/gaming-sets'),
(32,'kits','Kits', '/api/equipment-category/kits'),
(33,'land-vehicles','Land Vehicles', '/api/equipment-category/land-vehicles'),
(34,'tack-harness-and-drawn-vehicles','Tack, Harness, and Drawn Vehicles', '/api/equipment-category/tack-harness-and-drawn-vehicles'),
(35,'musical-instruments','Musical Instruments', '/api/equipment-category/musical-instruments'),
(36,'mounts-and-vehicles','Mounts and Vehicles', '/api/equipment-category/mounts-and-vehicles'),
(37,'mounts-and-other-animals','Mounts and Other Animals', '/api/equipment-category/mounts-and-other-animals'),
(38,'waterborne-vehicles','Waterborne Vehicles', '/api/equipment-category/waterborne-vehicles'),
(39,'wondrous-items','Wondrous Items', '/api/equipment-category/wondrous-items');
